"""empty message

Revision ID: 05376a8fe770
Revises: 2bd10211cd77
Create Date: 2022-07-14 20:38:45.273404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05376a8fe770'
down_revision = '2bd10211cd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_author')
    # ### end Alembic commands ###
