"""Initial Migration

Revision ID: 969249ee0ffd
Revises: 
Create Date: 2022-06-09 10:47:26.741291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969249ee0ffd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
